name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/**'
      - '!.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests
        run: ./gradlew test
      - name: Generate coverage
        if: ${{ matrix.java == 17 }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew jacocoTestReport coverallsJacoco