name: Releases

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests and upload release
        env:
          GH_PACKAGES_RELEASE_TOKEN: ${{ secrets.PACKAGES_RELEASE_TOKEN }}
        run: ./gradlew test publish -Prelease.version=$RELEASE_VERSION
      - name: Generate API documentation
        run: ./gradlew dokkaHtml -Prelease.version=$RELEASE_VERSION
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: lib/build/dokka